### ISSUE TITLE
Unknown location in user profile

### ISSUE THREAD

**Issue by Cu8eeeR** [Sama34/OUGC-Pages#7]
Unknown location in user profile during viewing OUGC custom page.

**Comment by groovybluedog** [comment]
I've just installed this and I find the same thing. Regardless of access permissions, and the "Show in Who's Online" setting which seems to do nothing, the Who's Online page and profiles show "Unknown Location" no matter if it's a category or page. 

Quite a serious bug too!

**Comment by Sama34** [comment]
Not that of a _serious issue_ though, your forum will not blow because somebody doesn't know which page somebody else is visiting, really.

**Comment by groovybluedog** [comment]
It won't blow up, but users will be confused, will question if I'm trying to hide something, and will go frantic on the forum and in my messages reporting bugs and things. To cause my users confusion is serious enough for me with the community I am trying to create. Not to mention it's hassle for me and my staff to see who's looking where; 20 different pages would all come up as the same thing, something that doesn't happen anywhere else in MyBB unless it actually is the same.

Anywho, any ideas if this would be solved at all?

**Comment by Sama34** [comment]
Sure it will be fixed, it is just not a priority. I will try to push a fix to the development branch.

**Comment by groovybluedog** [comment]
As with anything, it's really down to interpretation. Anyway, thanks, I'll stick it on my forum anyway as it should be as easy as overwriting the files once a patch is out, right? Otherwise an excellent plugin, especially with the permissions aspect.

Oh and what exactly does "hide from who's online" do? I.e. is it supposed to show unknown page, not show the user as online at all, show as viewing the Index page or something?

**Comment by Sama34** [comment]
IIRC it does shows the user as a guest visiting the index page.

**Comment by groovybluedog** [comment]
Any timescale for a fix yet?

**Comment by Sama34** [comment]
I was unable to fix it at the time, will come back at it soon.

**Comment by groovybluedog** [comment]
*pokes* - Shame your fix didn't work and sorry to be a pain but any luck yet? So badly want to use this plugin yet don't want to confuse my users with the Unknown location thing. Alternatively while we wait for a fix could "Unknown location" be altered to something like "Non-Forum Page - Click to view" or something? Thanks =D

**Comment by Sama34** [comment]
I'm currently working on a update for OUGC Awards on which I also need to implement WOL support, please buzz me next Thursday to sort this out.

**Comment by groovybluedog** [comment]
It's buzzing time! *pokes you* ;D

**Comment by Sama34** [comment]
I pushed a fix to this. Not surpriced it didn't work, ever. Please confirm it is fixed.
4d2e6e2035b65f32bdf26df6c7cfb62f3b2f4ceb

**Comment by groovybluedog** [comment]
I will try shortly and will get back to you by the end of the weekend, thanks!

**Comment by groovybluedog** [comment]
Sorry, got a little caught up in some other things, but confirmed working. Thanks!

**Comment by Cu8eeeR** [comment]
Works fine, thank you!
